# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26b9273cb7feac5721e4ec6e06295221727922e7fe25dff45a46d6e113fd04ff13f36ead19653c0b48a21ccf5e934ba152ea9ea37189e11465db7a721d9949fd

test:
  secret_key_base: 77c5762502b7c4297cd56ae1bc985dad6bb2ad7db8d4ebf00646ec936d23c1f88e310a8f25efa4f6770a03bffdf02d8192e9d7846d4c46a862e2461f3f9f1d4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
